=== java-prolog-connectivity/jpc.examples/src/main/resources/org/jpc/examples/metro/xml_docs/logtalk.dtd
<!--
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%  This file is part of Logtalk <http://logtalk.org/>  
%  Copyright (c) 1998-2014 Paulo Moura <pmoura@logtalk.org>
%
%  This program is free software: you can redistribute it and/or modify
%  it under the terms of the GNU General Public License as published by
%  the Free Software Foundation, either version 3 of the License, or
%  (at your option) any later version.
%  
%  This program is distributed in the hope that it will be useful,
%  but WITHOUT ANY WARRANTY; without even the implied warranty of
%  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%  GNU General Public License for more details.
%  
%  You should have received a copy of the GNU General Public License
%  along with this program.  If not, see <http://www.gnu.org/licenses/>.
%  
%  Additional licensing terms apply per Section 7 of the GNU General
%  Public License 3. Consult the `LICENSE.txt` file for details.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-->


<!ELEMENT logtalk (entity, relations, predicates, operators, remarks)>


<!ELEMENT entity (name, type, compilation, comment?, (parnames|parameters)?, author?, version?, date?, copyright?, license?, info*)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT compilation (#PCDATA)>

<!ELEMENT comment (#PCDATA)>

<!ELEMENT parnames (#PCDATA)>

<!ELEMENT parameters (parameter*)>

<!ELEMENT parameter (name, description)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT author (#PCDATA)>

<!ELEMENT version (#PCDATA)>

<!ELEMENT date (#PCDATA)>

<!ELEMENT copyright (#PCDATA)>

<!ELEMENT license (#PCDATA)>

<!ELEMENT info (key, value)>


<!ELEMENT key (#PCDATA)>

<!ELEMENT value (#PCDATA)>


<!ELEMENT relations (implements*, imports*, extends*, instantiates*, specializes*, uses*, calls*, alias*)>

<!ELEMENT implements (name, scope, file)>

<!ELEMENT imports (name, scope, file)>

<!ELEMENT extends (name, scope, file)>

<!ELEMENT instantiates (name, scope, file)>

<!ELEMENT specializes (name, scope, file)>

<!ELEMENT uses (name, file)>

<!ELEMENT calls (name, file)>

<!ELEMENT alias (name, original, alternative)>


<!ELEMENT scope (#PCDATA)>

<!ELEMENT file (#PCDATA)>

<!ELEMENT original (#PCDATA)>

<!ELEMENT alternative (#PCDATA)>


<!ELEMENT predicates (public, protected, private)>


<!ELEMENT public (predicate*)>

<!ELEMENT protected (predicate*)>

<!ELEMENT private (predicate*)>


<!ELEMENT predicate (name, scope, compilation, meta?, mode*, comment?, template?, (argnames|arguments)?, exceptions?, info*, examples?)>

<!ELEMENT meta (#PCDATA)>

<!ELEMENT mode (template, solutions)>

<!ELEMENT template (#PCDATA)>

<!ELEMENT solutions (#PCDATA)>

<!ELEMENT argnames (#PCDATA)>

<!ELEMENT arguments (argument*)>

<!ELEMENT argument (name, description)>

<!ELEMENT exceptions (exception*)>

<!ELEMENT exception (condition, term)>

<!ELEMENT condition (#PCDATA)>

<!ELEMENT term (#PCDATA)>

<!ELEMENT examples (example*)>

<!ELEMENT example (description, call, bindings)>

<!ELEMENT call (#PCDATA)>

<!ELEMENT bindings (#PCDATA)>

<!ELEMENT operators (operator*)>

<!ELEMENT operator (term, scope)>

<!ELEMENT remarks (remark*)>

<!ELEMENT remark (topic, text)>

<!ELEMENT topic (#PCDATA)>

<!ELEMENT text (#PCDATA)>


<!ENTITY % custom SYSTEM "custom.ent">

%custom;

=== java-prolog-connectivity/jpc.examples/src/main/resources/org/jpc/examples/metro/xml_docs/line_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE logtalk SYSTEM "logtalk.dtd">
<?xml-stylesheet type="text/xsl" href="lgtxml.xsl"?>
<logtalk>
<entity>
<name><![CDATA[line(Name)]]></name>
<type>object</type>
<compilation>static, context_switching_calls</compilation>
<comment><![CDATA[A metro line]]></comment>
<parameters>
<parameter>
<name><![CDATA[Name]]></name>
<description><![CDATA[The name of the metro line]]></description>
</parameter>
</parameters>
<author><![CDATA[Sergio Castro]]></author>
</entity>
<relations>
</relations>
<predicates>
<public>
<predicate>
<name><![CDATA[name/1]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Name is the line name.]]></comment>
<template><![CDATA[name(Name)]]></template>
</predicate>
<predicate>
<name><![CDATA[connects/2]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Station1 is connected to Station2 by means of this line.]]></comment>
<template><![CDATA[connects(Station1,Station2)]]></template>
</predicate>
<predicate>
<name><![CDATA[add_connection/2]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Station1 is now connected to Station2 by means of this line.]]></comment>
<template><![CDATA[add_connection(Station1,Station2)]]></template>
</predicate>
</public>
<protected>
</protected>
<private>
</private>
</predicates>
<operators>
</operators>
<remarks>
</remarks>
</logtalk>

=== java-prolog-connectivity/jpc.examples/src/main/resources/org/jpc/examples/metro/xml_docs/station_1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE logtalk SYSTEM "logtalk.dtd">
<?xml-stylesheet type="text/xsl" href="lgtxml.xsl"?>
<logtalk>
<entity>
<name><![CDATA[station(Name)]]></name>
<type>object</type>
<compilation>static, context_switching_calls, dynamic_declarations</compilation>
<comment><![CDATA[A metro station]]></comment>
<parameters>
<parameter>
<name><![CDATA[Name]]></name>
<description><![CDATA[The name of the station]]></description>
</parameter>
</parameters>
<author><![CDATA[Sergio Castro]]></author>
</entity>
<relations>
</relations>
<predicates>
<public>
<predicate>
<name><![CDATA[name/1]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Name is the station name.]]></comment>
<template><![CDATA[name(Name)]]></template>
</predicate>
<predicate>
<name><![CDATA[connected/1]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Station is a connected station.]]></comment>
<template><![CDATA[connected(Station)]]></template>
</predicate>
<predicate>
<name><![CDATA[connected/2]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Station is a connected station by means of Line.]]></comment>
<template><![CDATA[connected(Station,Line)]]></template>
</predicate>
<predicate>
<name><![CDATA[nearby/1]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Station is a nearby station.]]></comment>
<template><![CDATA[nearby(Station)]]></template>
</predicate>
<predicate>
<name><![CDATA[reachable/1]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Station is a reachable station.]]></comment>
<template><![CDATA[reachable(Station)]]></template>
</predicate>
<predicate>
<name><![CDATA[reachable/2]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Station is a reachable station by means of traversing IntermediateStations.]]></comment>
<template><![CDATA[reachable(Station,IntermediateStations)]]></template>
</predicate>
</public>
<protected>
</protected>
<private>
</private>
</predicates>
<operators>
</operators>
<remarks>
</remarks>
</logtalk>

=== java-prolog-connectivity/jpc.examples/src/main/resources/org/jpc/examples/metro/xml_docs/metro_0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE logtalk SYSTEM "logtalk.dtd">
<?xml-stylesheet type="text/xsl" href="lgtxml.xsl"?>
<logtalk>
<entity>
<name><![CDATA[metro]]></name>
<type>object</type>
<compilation>static, context_switching_calls</compilation>
<comment><![CDATA[The London metro. Adapted from the "Simply Logical" book by Peter Flach.]]></comment>
<author><![CDATA[Sergio Castro]]></author>
</entity>
<relations>
</relations>
<predicates>
<public>
<predicate>
<name><![CDATA[connected/3]]></name>
<scope>public</scope>
<compilation>dynamic</compilation>
<comment><![CDATA[Station1 is connected to Station2 by means of Line.]]></comment>
<template><![CDATA[connected(Station1,Station2,Line)]]></template>
</predicate>
<predicate>
<name><![CDATA[nearby/2]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Station1 is nearby Station2.]]></comment>
<template><![CDATA[nearby(Station1,Station2)]]></template>
</predicate>
<predicate>
<name><![CDATA[reachable/3]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Station2 is reachable from Station1 by means of traversing IntermediateStations.]]></comment>
<template><![CDATA[reachable(Station1,Station2,IntermediateStations)]]></template>
</predicate>
<predicate>
<name><![CDATA[line/1]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Name is the name of a Line.]]></comment>
<template><![CDATA[line(Name)]]></template>
</predicate>
<predicate>
<name><![CDATA[remove_all/0]]></name>
<scope>public</scope>
<compilation>static</compilation>
<comment><![CDATA[Removes all the lines.]]></comment>
</predicate>
</public>
<protected>
</protected>
<private>
</private>
</predicates>
<operators>
</operators>
<remarks>
</remarks>
</logtalk>
